### ISSUE TITLE
New Release of Home assistant Broke This

### ISSUE THREAD

**Issue by CAVACO-PT** [veista/smartthings#68]
Hi , the new release from HA  2023.5 , broke this integration , here is the logs , can anyone help ?

Logger: homeassistant.config_entries
Source: custom_components/smartthings/__init__.py:186
Integration: SmartThings
First occurred: 10:02:43 PM (1 occurrences)
Last logged: 10:02:43 PM

Error setting up entry Casa for smartthings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthings/__init__.py", line 186, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by mrbrunopardal** [comment]
Yes, same problem here! We very appreciate a fix ;) thank you!

**Comment by Cruguah** [comment]
Fix is available in PR #61, @veista just needs to aprove this and merge it into main!

**Comment by daath** [comment]
Just spent an hour trying to figure out what was going on and ended up here :) I hope @veista merges this asap!

**Comment by CAVACO-PT** [comment]
@veista  i had to delete the integration , and add the default one for smarthings , that was got a few things only , just becasue i need the main AC control to work at least with automations , even if all the other things are missing , can u please help us in aproving this so  , many thanks to all

**Comment by mrkaqz** [comment]
Yes, it broke the integration. I have try remove and re-setup integration but still gave error below.

Home Assistant Core
Error setting up entry Cattus for smartthings
9:29:42 PM – (ERROR) SmartThings (custom integration)
Failed to create subscription for 'audioMute' under app 'xxxxxxx-xxxx-xxxxx-xxxx-xxxxxx': Unprocessable Entity (422): {"requestId":  'xxxxxxx-xxxx-xxxxx-xxxx-xxxxxx', "error": {"code": "LimitError", "message": "subscription limit exceeded", "details": []}}
9:29:42 PM – (ERROR) SmartThings (custom integration) - message first occurred at 9:29:42 PM and shows up 6 times
Some device attributes may not receive push updates and there may be subscription creation failures under app ' 'xxxxxxx-xxxx-xxxxx-xxxx-xxxxxx' because 52 subscriptions are required but there is a limit of 40 per app
9:29:41 PM – (WARNING) SmartThings (custom integration)

**Comment by Oneshotblu** [comment]
Thank you very much Veista!
